name: notustohtml
description: Convert the Notus document format to an HTML representation.
publish_to: 'none'
version: 0.0.8
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  notus_format: ^1.0.3
  flutter_quill:
    git:
      url: https://github.com/VadimBliz/flutter-quill.git
  html: ^0.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  test:
